Use static assert instead of preprocessor directives
The pattern (c1 ? v1 : c2 ? v2 : v3) in a preprocessor conditional expression
triggers a preprocessor bug in MSVC
```
fatal error C1012: unmatched parenthesis: missing ')'
```
even with Visual Studio 2019 and `/Zc:preprocessor`. Avoid this pattern.

Signed-off-by: Gilles Peskine <Gilles.Peskine@arm.com>